apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: atlas-user-1
  namespace: atlas
spec:
  instanceRef:
    name: my-atlas-cluster
  parameters:
    user:
      roles:
      - databaseName: sample_airbnb
        collectionName: listingsAndReviews
        roleName: readWrite
      - databaseName: sample_geospatial
        collectionName: shipwrecks
        roleName: dbAdmin
      - databaseName: sample_mflix
        collectionName: movies
        roleName: dbAdmin
